SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN (SELECT B.BOOK_ID, SUM(S.SALES*B.PRICE) AS SALES FROM BOOK_SALES S JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID WHERE DATE_FORMAT(S.SALES_DATE,'%Y-%m')='2022-01' GROUP BY S.BOOK_ID) AS S ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.AUTHOR_ID,B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC;

