-- 코드를 입력하세요
SELECT TEMP.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM 
(SELECT B.AUTHOR_ID, B.CATEGORY, SUM(S.SALES*PRICE) AS TOTAL_SALES
 FROM BOOK B, BOOK_SALES S
 WHERE B.BOOK_ID = S.BOOK_ID AND DATE_FORMAT(S.SALES_DATE,"%Y-%m") = '2022-01'
 GROUP BY B.AUTHOR_ID, B.CATEGORY
) TEMP, AUTHOR A
WHERE TEMP.AUTHOR_ID = A.AUTHOR_ID
ORDER BY 1, 3 DESC
