SELECT A.ID,IF(B.CHILD_COUNT IS NULL, 0, B.CHILD_COUNT ) AS CHILD_COUNT
FROM ECOLI_DATA A LEFT JOIN (SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT FROM ECOLI_DATA
GROUP BY PARENT_ID) AS B
ON A.ID = B.PARENT_ID
WHERE A.ID IS NOT NULL
ORDER BY A.ID;
