-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, (P.PRICE*TEMP.TOTAL_AMOUNT) AS SALES
FROM (SELECT P.PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
FROM PRODUCT P JOIN OFFLINE_SALE S
ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_ID) AS TEMP JOIN PRODUCT P
ON TEMP.PRODUCT_ID = P.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE;