-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100) FEE
FROM 
(SELECT CAR_ID, CAR_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE IN ('세단','SUV')) C 
JOIN
(SELECT DISTINCT CAR_ID
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE CAR_ID NOT IN 
    (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')) H
ON C.CAR_ID = H.CAR_ID
JOIN
CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100 >= 500000 AND DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100 < 2000000
 ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC


