-- 코드를 입력하세요
SELECT R.FOOD_TYPE, REST_ID, REST_NAME, R.FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) TEMP, REST_INFO R
WHERE TEMP.FOOD_TYPE = R.FOOD_TYPE AND TEMP.FAVORITES = R.FAVORITES
ORDER BY FOOD_TYPE DESC