-- 코드를 작성해주세요
SELECT ID, 
    CASE
        WHEN PR <= 25 THEN 'CRITICAL'
        WHEN PR <= 50 THEN 'HIGH'
        WHEN PR <= 75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, (PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)*100) AS PR
    FROM ECOLI_DATA
) E
ORDER BY ID;