SELECT ID, CASE WHEN COLONY_NAME <=0.25 THEN 'CRITICAL'
WHEN COLONY_NAME <=0.5 THEN 'HIGH'
WHEN COLONY_NAME <=0.75 THEN 'MEDIUM'
ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS COLONY_NAME FROM ECOLI_DATA) AS D
ORDER BY ID;
