SELECT USER_ID, NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS  '전체주소', CONCAT_WS('-',LEFT(TLNO,3),RIGHT(LEFT(TLNO,7),4),RIGHT(TLNO,4)) AS '전화번호'
FROM USED_GOODS_USER U
WHERE USER_ID IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(*) >= 3)
ORDER BY 1 DESC;