SELECT YEAR(S.SALES_DATE) AS YEAR,MONTH(S.SALES_DATE) AS MONTH,U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE S JOIN (SELECT USER_ID, GENDER FROM USER_INFO WHERE GENDER IS NOT NULL) U
ON S.USER_ID = U.USER_ID
GROUP BY YEAR(S.SALES_DATE),MONTH(S.SALES_DATE),U.GENDER
ORDER BY YEAR(S.SALES_DATE),MONTH(S.SALES_DATE),U.GENDER