-- 코드를 입력하세요
SELECT TEMP.YEAR, TEMP.MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) USERS
FROM USER_INFO U, (SELECT USER_ID, YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH
FROM ONLINE_SALE) TEMP
WHERE U.USER_ID = TEMP.USER_ID AND U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER