SELECT T.CAR_ID, ROUND(T.DAY,1) AS AVERAGE_DURATION
FROM(SELECT *, AVG(DATEDIFF(END_DATE,START_DATE)+1) AS DAY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 GROUP BY CAR_ID) AS T
WHERE T.DAY >= 7
ORDER BY 2 DESC, 1 DESC;