SELECT DISTINCT A.CAR_ID, IFNULL(B.AVAILABILITY,'대여 가능')AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A LEFT JOIN (SELECT CAR_ID,'대여중'AS AVAILABILITY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE '2022-10-16' BETWEEN  START_DATE AND END_DATE GROUP BY CAR_ID)B
ON A.CAR_ID = B.CAR_ID
ORDER BY A.CAR_ID DESC
