SELECT ECOLI_DATA.QUARTER, COUNT(*) AS ECOLI_COUNT
FROM (SELECT *, (CASE WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m') < 4 THEN '1Q'
                    WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m') < 7 THEN '2Q'
                 WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m') < 10 THEN '3Q'
                 ELSE '4Q' END) AS QUARTER
      FROM ECOLI_DATA) AS ECOLI_DATA
GROUP BY ECOLI_DATA.QUARTER
ORDER BY ECOLI_DATA.QUARTER;