SELECT FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, FOOD_PRODUCT.PRICE*SUM(FOOD_ORDER.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT JOIN FOOD_ORDER
ON FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
WHERE DATE_FORMAT(FOOD_ORDER.PRODUCE_DATE,'%Y-%m') = '2022-05'
GROUP BY FOOD_PRODUCT.PRODUCT_ID
ORDER BY 3 DESC, 1;