-- 코드를 입력하세요
SELECT O.PRODUCT_ID, F.PRODUCT_NAME, O.AMOUNT*F.PRICE TOTAL_SALES
FROM(SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
FROM FOOD_ORDER
WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m')='2022-05'
GROUP BY PRODUCT_ID) O INNER JOIN FOOD_PRODUCT F
ON O.PRODUCT_ID = F.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID