SELECT T.FLAVOR
FROM (SELECT FLAVOR,SUM(TOTAL_ORDER) AS S FROM FIRST_HALF GROUP BY FLAVOR
UNION ALL SELECT FLAVOR,SUM(TOTAL_ORDER) AS S FROM JULY GROUP BY FLAVOR) AS T
GROUP BY T.FLAVOR
ORDER BY SUM(T.S) DESC
LIMIT 3;