WITH RECURSIVE CTE(HOUR) AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 AS HOUR FROM CTE WHERE HOUR<23
)
SELECT CTE.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM CTE LEFT JOIN ANIMAL_OUTS AS A
ON CTE.HOUR = HOUR(A.DATETIME)
GROUP BY CTE.HOUR