-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, PRICE AS TOTAL_SALES
FROM (SELECT WRITER_ID, SUM(PRICE) AS PRICE FROM USED_GOODS_BOARD WHERE STATUS = 'DONE' GROUP BY WRITER_ID) AS B JOIN USED_GOODS_USER AS U
ON WRITER_ID = USER_ID
WHERE PRICE >= 700000
ORDER BY TOTAL_SALES;
