-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, T.TOTAL AS TOTAL_SALES
FROM USED_GOODS_USER U JOIN
(SELECT U.USER_ID, SUM(PRICE) AS TOTAL
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY U.USER_ID
HAVING SUM(PRICE) >= 700000) AS T
ON U.USER_ID = T.USER_ID
ORDER BY TOTAL_SALES;