-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, TEMP.PRICE AS TOTAL_SALES
FROM (
    SELECT WRITER_ID, SUM(PRICE) PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) TEMP, USED_GOODS_USER U
WHERE TEMP.WRITER_ID = U.USER_ID
ORDER BY 3
