SELECT E.EMP_NO, E.EMP_NAME, G.GRADE, (E.SAL*G.BONUS/100)AS BONUS
FROM HR_EMPLOYEES E
JOIN (SELECT EMP_NO, CASE WHEN AVG(SCORE)>=96 THEN 20
    WHEN AVG(SCORE)>=90 THEN 15
    WHEN AVG(SCORE)>=80 THEN 10
    ELSE 0 END AS BONUS,
      CASE WHEN AVG(SCORE)>=96 THEN 'S'
    WHEN AVG(SCORE)>=90 THEN 'A'
    WHEN AVG(SCORE)>=80 THEN 'B'
    ELSE 'C' END AS GRADE
FROM HR_GRADE
GROUP BY EMP_NO) AS G
ON E.EMP_NO = G.EMP_NO
ORDER BY E.EMP_NO;