-- 코드를 작성해주세요
SELECT E.EMP_NO, E.EMP_NAME, TEMP.GRADE,
CASE WHEN GRADE = 'S' THEN SAL*20/100
WHEN GRADE = 'A' THEN SAL*15/100
WHEN GRADE = 'B' THEN SAL*10/100
ELSE 0 END AS BONUS
FROM 
(SELECT EMP_NO, CASE
 WHEN AVG(SCORE) >= 96 THEN 'S'
 WHEN AVG(SCORE) >= 90 THEN 'A'
 WHEN AVG(SCORE) >= 80 THEN 'B'
 ELSE 'C'
 END AS GRADE
 FROM HR_GRADE
GROUP BY EMP_NO) TEMP, HR_EMPLOYEES E
WHERE TEMP.EMP_NO = E.EMP_NO
ORDER BY E.EMP_NO