# SELECT ITEM_TREE.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
# FROM ITEM_INFO LEFT JOIN ITEM_TREE
# ON ITEM_INFO.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
# WHERE ITEM_INFO.RARITY = 'RARE'
# ORDER BY ITEM_TREE.ITEM_ID DESC
SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
FROM ITEM_INFO,(SELECT ITEM_ID
FROM ITEM_TREE
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')) AS T
WHERE ITEM_INFO.ITEM_ID = T.ITEM_ID
ORDER BY ITEM_INFO.ITEM_ID DESC
