-- 코드를 입력하세요
SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
GROUP BY CAR_ID
HAVING COUNT(*) >= 5) AS C
ON H.CAR_ID = C.CAR_ID
WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
GROUP BY H.CAR_ID, MONTH(H.START_DATE)
ORDER BY MONTH(H.START_DATE), H.CAR_ID DESC;
