SELECT Y.YEAR, (Y.MAX_LENGTH - D.SIZE_OF_COLONY) AS YEAR_DEV, D.ID
FROM ECOLI_DATA D JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_LENGTH FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) AS Y
ON YEAR(D.DIFFERENTIATION_DATE) = Y.YEAR
ORDER BY 1, 2;
