-- 코드를 작성해주세요
SELECT E1.YEAR, (SIZE-SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM(
    SELECT ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR FROM ECOLI_DATA
) E1, (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) E2
WHERE E1.YEAR = E2.YEAR
ORDER BY YEAR, YEAR_DEV