SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO JOIN (SELECT * FROM FISH_NAME_INFO
WHERE FISH_NAME_INFO.FISH_NAME = 'BASS' OR FISH_NAME_INFO.FISH_NAME = 'SNAPPER') AS FISH_NAME_INFO
ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE;