SELECT A.FLAVOR
FROM (SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF WHERE TOTAL_ORDER>3000) A, ICECREAM_INFO
WHERE A.FLAVOR = ICECREAM_INFO.FLAVOR AND INGREDIENT_TYPE='fruit_based'
ORDER BY TOTAL_ORDER DESC;