-- 코드를 작성해주세요
SELECT ID, TEMP.FISH_NAME, TEMP.LENGTH
FROM(
    SELECT FISH_NAME, N.FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO I INNER JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY N.FISH_TYPE, FISH_NAME
    ) TEMP INNER JOIN FISH_INFO I
    ON TEMP.FISH_TYPE = I.FISH_TYPE AND TEMP.LENGTH= I.LENGTH
ORDER BY ID;