-- 코드를 작성해주세요
SELECT S.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
) S
ON E.EMP_NO = S.EMP_NO;

