-- 코드를 작성해주세요
SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(E.SAL) AVG_SAL
FROM HR_DEPARTMENT D, 
(SELECT DEPT_ID, AVG(SAL) SAL
FROM HR_EMPLOYEES
GROUP BY DEPT_ID) E
WHERE D.DEPT_ID = E.DEPT_ID
ORDER BY E.SAL DESC;
