SELECT BOOK.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES JOIN BOOK
ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
WHERE DATE_FORMAT(BOOK_SALES.SALES_DATE,'%Y-%m')='2022-01'
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY;