-- 코드를 입력하세요
SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM (
    SELECT CATEGORY, MAX(PRICE) PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) TEMP, FOOD_PRODUCT F
WHERE TEMP.CATEGORY = F.CATEGORY AND TEMP.PRICE = F.PRICE
ORDER BY PRICE DESC