-- 코드를 작성해주세요
SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM (
    SELECT ID, FISH_TYPE,LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    UNION
    SELECT ID, FISH_TYPE, 10 LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NULL
) AS TEMP
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE
